/** Channel names shared by the main process and the preload bridge. */
export const IPC = {
  getSnapshot: 'videocat:get-snapshot',
  addUrl: 'videocat:add-url',
  chooseFormat: 'videocat:choose-format',
  setItemSubtitles: 'videocat:set-item-subtitles',
  pause: 'videocat:pause',
  resume: 'videocat:resume',
  retry: 'videocat:retry',
  cancel: 'videocat:cancel',
  pauseAll: 'videocat:pause-all',
  resumeAll: 'videocat:resume-all',
  updateSettings: 'videocat:update-settings',
  chooseDownloadDirectory: 'videocat:choose-download-directory',
  openDownloadFolder: 'videocat:open-download-folder',
  openFile: 'videocat:open-file',
  revealFile: 'videocat:reveal-file',
  removeHistoryEntry: 'videocat:remove-history-entry',
  clearHistory: 'videocat:clear-history',
  readClipboardUrl: 'videocat:read-clipboard-url',
  dismissClipboardHit: 'videocat:dismiss-clipboard-hit',
  updateEngine: 'videocat:update-engine',
  checkForUpdates: 'videocat:check-for-updates',
  installUpdate: 'videocat:install-update',
  openExternal: 'videocat:open-external',
  getVersion: 'videocat:get-version',
  getPlatform: 'videocat:get-platform',
  // main -> renderer
  onQueue: 'videocat:queue',
  onHistory: 'videocat:history',
  onSettings: 'videocat:settings',
  onDisk: 'videocat:disk',
  onEngine: 'videocat:engine',
  onClipboardHit: 'videocat:clipboard-hit',
  onUpdate: 'videocat:update-status',
  onToast: 'videocat:toast'
} as const
