/** Channel names shared by the main process and the preload bridge. */
export const IPC = {
  getSnapshot: 'grabbit:get-snapshot',
  addUrl: 'grabbit:add-url',
  chooseFormat: 'grabbit:choose-format',
  setItemSubtitles: 'grabbit:set-item-subtitles',
  pause: 'grabbit:pause',
  resume: 'grabbit:resume',
  retry: 'grabbit:retry',
  cancel: 'grabbit:cancel',
  pauseAll: 'grabbit:pause-all',
  resumeAll: 'grabbit:resume-all',
  updateSettings: 'grabbit:update-settings',
  chooseDownloadDirectory: 'grabbit:choose-download-directory',
  openDownloadFolder: 'grabbit:open-download-folder',
  openFile: 'grabbit:open-file',
  revealFile: 'grabbit:reveal-file',
  removeHistoryEntry: 'grabbit:remove-history-entry',
  clearHistory: 'grabbit:clear-history',
  readClipboardUrl: 'grabbit:read-clipboard-url',
  dismissClipboardHit: 'grabbit:dismiss-clipboard-hit',
  updateEngine: 'grabbit:update-engine',
  openExternal: 'grabbit:open-external',
  getVersion: 'grabbit:get-version',
  getPlatform: 'grabbit:get-platform',
  // main -> renderer
  onQueue: 'grabbit:queue',
  onHistory: 'grabbit:history',
  onSettings: 'grabbit:settings',
  onDisk: 'grabbit:disk',
  onEngine: 'grabbit:engine',
  onClipboardHit: 'grabbit:clipboard-hit',
  onToast: 'grabbit:toast'
} as const
